### ISSUE TITLE
Moonlight-II for atom with TS support

### ISSUE THREAD

**Issue by alfonsocv12** [atomiks/moonlight-vscode-theme#35]
Hi, Atomiks I used VSCode Only because of your moonlight II theme and the fact that It has been the best with TypeScript. Today I just had enough of the horrible UI design of VSCode and wanted to go back to Atom, but I remember why I was using VSCode at the beginning. Try installing the Atom version of moonlight but has horrible typescript support.

I have cloned both of your repositories and tried binding them to fix the issue with no success I don't know if you could help with this, if you are interested, or if you have any problem with me doing this. Please let me know in that case.

**Comment by atomiks** [comment]
Atom has the legacy Moonlight theme which is a lot different to the VS Code versions & I haven't updated it for 4 years. I stubbornly switched to VS Code in 2018 but the UI was so poor compared to Atom (and barely customizable), I think I just got used to it though. I don't know anything about making Atom extensions anymore and don't have the energy to work on it.

I recently tried Atom again late last year, but it has barely any support for extensions, TS IntelliSense, runs slow, is infrequently getting updates, and VS Code got better visually since then. Maybe https://zed.dev/ can improve the text editor space!

**Comment by alfonsocv12** [comment]
I understand trying to create my own moonlight support for Atom it was so overwhelming. Yes, Atom is ultra dying. Well, I let you know if I get the energy to port this out hope that zed.dev it's good, and see your theme there. Have a great day

**Comment by atomiks** [comment]
Atom was discontinued in Dec. 22
