### ISSUE TITLE
Issue with the editor background color

### ISSUE THREAD

**Issue by donatoaguirre24** [atomiks/moonlight-vscode-theme#5]
Hi, first of all, congratulations, the theme looks really awesome and the color composition it's very well achieved. 

The only issue I found is a weird behavior with the background of the editor. It's shown a darker rectangle at the right side, in almost every file that I opened. 

I gonna attach a screenshot for illustration purposes. 

![image](https://user-images.githubusercontent.com/20030075/58768751-4ca49380-8576-11e9-99b3-1c1638a4ed62.png)

**Comment by atomiks** [comment]
Ughh yes I noticed that too with the new Electron color profile upgrade in February. I don't know why it occurs... since it's not noticeable on the default theme for example.

I've been staying on 1.30.2 which has much more vibrant colors and doesn't have that problem. https://github.com/Microsoft/vscode/issues/68001#issuecomment-461318004

If there's a fix for it for the new versions please make a PR!

**Comment by atomiks** [comment]
https://github.com/Microsoft/vscode/issues/48043

I found this issue. It seems they fixed it a year ago but the February update caused problems again, but it's fixed in Electron 4.x which should be out in the June release (early July I think?)

Not sure why there hasn't been a new issue on it though. Maybe because it's not very noticeable

**Comment by atomiks** [comment]
Okay so weirdly enough, only colors right around the `editor.background` color I chose for this theme causes the artifact problem. If you change any theme's background color to this theme's exact background color, the problem occurs.

For now, you can change `editor.background` to a different color.  e.g. Palenight's `    "editor.background": "#292D3E"`

It sucks because I tried my best to find the perfect background color, and that one is too light for me, and if I try to just move the color picker a few pixels from this theme's current background color, it's not enough to fix it. It's like a whole vicinity of colors around it that is buggy. 

Anyway, as I said I'm pretty sure July 2019 release will fix this, so unfortunately we might need to wait.

**Comment by donatoaguirre24** [comment]
I tried changing the color to the one that you put above and it fixed the problem. I agree with you that the current color of the background is the best one. 

I gonna wait, hope that the July release will fix it. Thanks for your response and to take the time to research the issue.

**Comment by donatoaguirre24** [comment]
I tried the exploration build of VS Code that uses Electron 4, and as you say the problem it's fixed 👍

**Comment by atomiks** [comment]
Fixed in latest stable it seems
